name: Build & Release

on:
  push:
    branches:
      - master

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: ['14.0.0', '14', '16.0.0', '16']

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - name: Node version
        run: node --version

      - name: Install dependencies
        run: rm -rf node_modules && yarn install --frozen-lockfile
      - name: Lint
        run: yarn run lint
      - name: Build
        run: yarn run build
      - name: Test
        run: yarn test

  release:
    name: Release
    runs-on: ubuntu-20.04
    needs: build-test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v3.1.1
        with:
          cache: 'yarn'
      - name: Node version
        run: node --version

      - name: Install dependencies
        run: rm -rf node_modules && yarn install --frozen-lockfile
      - name: Build
        run: yarn run build
      - name: Test
        run: yarn test
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          tag: v1.17.4
