# Uses https://github.com/marketplace/actions/labeler

name: 'Pull Request Labeler'
on:
  - pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: yarn run lint
      - name: Build
        run: yarn run build
      - name: Test
        run: yarn test
