# Uses https://github.com/marketplace/actions/labeler

name: 'Pull Request Labeler'
on:
  - pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn run build
      - name: Test
        run: yarn test
